name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Деплой будет запускаться при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Клонирует репозиторий

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Устанавливает Python 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt  # Устанавливает зависимости

    - name: Package Lambda function
      run: |
        zip -r9 function.zip .  # Упаковывает весь код в ZIP

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws lambda update-function-code --function-name telegram-subscriber-tracker --zip-file fileb://function.zip --region eu-north-1  # Обновляет код функции Lambda
